services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: ["flask","--app","run.py","run","--host=0.0.0.0","--port=5000"]
